<a href="https://colab.research.google.com/github/HabibaAbdelaziz/Numpy-Crash-Course-Notes/blob/main/Numpy_Crash_Course_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]
[[4 6 7]
 [6 6 6]]


In [ ]:
b = np.array([[4,6,7],[6,6,6]])
print(b)

[[4 6 7]
 [6 6 6]]


In [ ]:
a.ndim # get Dimension of array a


(3,)

In [ ]:
b.shape # get shape of array b. It is (2, 3) because we have two components. Inside each component, there are 3 elements.

(2, 3)

In [ ]:
c = np.array(([3,3,3],[4,4,4]), dtype='int16')
c.dtype # get type of array c

dtype('int16')

In [ ]:
c.itemsize # get size of array c elements. Since c has type int16, then size will be two bytes. If it was type int32, then c would have size 4 bytes/

2

In [ ]:
c.nbytes # get total size of c

12

# **Accessing/ Changing Specific Elements, Columns, Rows, etc.**

# **Initializing Different Types of Arrays**

In [ ]:
np.zeros(5) # all zeros matrix


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3)) # all zeros matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,6), 99, dtype='float32') # filling the matrix with any other number. First param is the dimension. Second param is the number we want to fill the matrix with

array([[99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99.]], dtype=float32)

In [ ]:
np.full_like(a, 4) # use another array to fill

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(4,3) # generate a (4,3) matric with random floats

array([[0.9592672 , 0.28972264, 0.00798287],
       [0.89714371, 0.75796808, 0.88812948],
       [0.02957589, 0.50749725, 0.68517381],
       [0.90571597, 0.37957778, 0.22360646]])

In [ ]:
np.random.randint(7, size=(3,9)) # fill with random ints. First param is max limit of the rand nums. Second Param is dimension of new matrix.

array([[1, 4, 2, 2, 4, 3, 2, 1, 6],
       [1, 4, 1, 1, 6, 6, 3, 2, 5],
       [0, 4, 0, 0, 0, 6, 5, 6, 3]])

In [ ]:
np.identity(6) # create identity matrix of size nxn

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0) # repeat arr 3 times
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# **BE CAREFUL WHEN COPYING ARRAYS!!!**
If you don't use the .copy function, then the array is copied by refrence not by value. So if you change b, a will be changed automatically because both are pointing to the same array.

In [ ]:
a = np.array([1,2,3])
b = a.copy() # must use copy() to not mess with array a when changing array b
b[0] = 100

print("a is: ",a)
print("b is: ",b)

a is:  [1 2 3]
b is:  [100   2   3]


In [ ]:
a + 2 # add 2 to every element in 'a'. Same goes for -,/,*

array([3, 4, 5])

# **Linear Algebra**

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # mult two matrices. col num of first matrix must be same as row num of second matrix


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c) # find the determinant of c

1.0

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# **Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

np.min(stats) # get the min value in stats

1

In [ ]:
np.min(stats, axis=0) # get the min value among all rows.

array([1, 2, 3])

In [ ]:
np.min(stats, axis=1) # get the min value in each column.

array([1, 4])

# **Reorganising Arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2 )) # reshape the matrix
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors. Size of the arrays must match to be stacked later on
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2]) # v1 will be stacked on top of v2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

# **Miscellaneous**

Load Data from file

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# **Boolean Masking and Advanced Indexing**

In [ ]:
filedata > 50 # show if value at each index is greater than 50.


array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata > 50] # grad the numbers in the array that are greater than 50


array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [ ]:
np.any(filedata > 50, axis = 0) # Axis = 0 means vertical. If ANY element of each column is greater than 50, output True for that column index.

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata > 50, axis = 0) # Axis = 0 means vertical. If ALL element of current column is greater than 50, output True for that column index.

In [ ]:
np.all(filedata > 50, axis=1) # Axis = 1 is Horizontal. If ALL elements of current row is greater than 50, output True for current row index.

array([False, False, False])

# **Problem 2 (See image attached to this Notebook)**